### PR TITLE
fixed Badge based on figma changes

### LINKED ISSUE #242: badge design changes
https://www.figma.com/file/oeHqO9qLCkz7SYb73J5Qx4/Receiver-Design-File?node-id=1107%3A16697&t=RbCuvl5UECRXoV3F-4

### PR DESCRIPTION
**Pull request by CsillagK**
Closes #242

### CODE REVIEW

File: src/lib/design/Badge.tsx [hunk 1]
```diff
@@ -1,36 +1,60 @@
-import styled from "styled-components";
+import styled, {css} from "styled-components";
 import {receiverTheme} from "@/lib/design/wip/receiverTheme";
 import {textXsMedium} from "@/lib/design/wip/typography";
 
 
 const Root = styled.div`
```
Comment (Norbert-EE) [inline src/lib/design/Badge.tsx:6]: We don't need this wrapper, can you pls remove it?

File: src/lib/design/Badge.tsx [hunk 2]
```diff
@@ -1,36 +1,60 @@
...
+  height: 0.375rem;
+  border-radius: 50%;
+  background-color: ${receiverTheme.colors.primary["500"]};
+
+  ${props => props.color === "gray" && css`
+    background-color: ${receiverTheme.colors.gray["700"]}
+  `};
 `;
 
 const LoadingDiv = styled.div`
```
Comment (Norbert-EE) [inline src/lib/design/Badge.tsx:44]: Background doesn't look the same as the design. If we use color gradient, we need the add one more line to our css.
`mix-blend-mode: multiply;`

File: src/lib/design/Badge.tsx [hunk 3]
```diff
@@ -1,36 +1,60 @@
...
 
-export const Badge = ({isLoading, label}: { isLoading: boolean, label: string }) => {
+export const Badge = ({
+                          isLoading,
+                          label,
+                          color,
+                          dot
+                      }: { isLoading: boolean, label: string, color: "gray" | "purple", dot: boolean }) => {
 
     if (isLoading) {
```
Comment (Norbert-EE) [inline src/lib/design/Badge.tsx:59]: Can we swap the logic on this? It should take a prop like hasLoaded and if it's true we can show the component with data, otherwise show the loading state.

**Review by matejcsok-ee — APPROVED** [review]
